name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  PROJECT_PATH: ReleaseZipper/ReleaseZipper.csproj
  BUILD_CONFIG: Release
  RUNTIME_ID: win-x64
  OUTDIR: ReleaseZipper/ReleaseZipper/bin/Release/net8.0-windows/win-x64/publish
  ZIPNAME: ReleaseZipper-${{ github.ref_name }}.zip
  ZIPPATH: ReleaseZipper/ReleaseZipper/bin/Release/net8.0-windows/${{ env.ZIPNAME }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build and Publish (single file, self-contained)
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} -c ${{ env.BUILD_CONFIG }} -r ${{ env.RUNTIME_ID }} --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - name: List published files for debug
        run: ls -lh ${{ env.OUTDIR }}

      - name: Create ZIP file
        run: |
          cd ${{ env.OUTDIR }}
          7z a ../../${{ env.ZIPNAME }} *

      - name: List ZIP in release directory for debug
        run: ls -lh ReleaseZipper/ReleaseZipper/bin/Release/net8.0-windows

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIPPATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
