name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ReleaseZipper/ReleaseZipper.csproj

      - name: Build and Publish
        run: |
          dotnet publish ReleaseZipper/ReleaseZipper.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - name: List files in publish directory
        run: ls -lh ReleaseZipper/ReleaseZipper/bin/Release/net8.0-windows/win-x64/publish

      - name: Zip published files
        run: |
          cd ReleaseZipper/ReleaseZipper/bin/Release/net8.0-windows/win-x64/publish
          7z a ../../ReleaseZipper-${{ github.ref_name }}.zip *

      - name: List ZIP in release directory
        run: ls -lh ReleaseZipper/ReleaseZipper/bin/Release/net8.0-windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./ReleaseZipper/ReleaseZipper/bin/Release/net8.0-windows/ReleaseZipper-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
