name: Build and Release

on:
  push:
    tags:
      - 'v*' # Dispara o workflow em tags como v1.0, v1.2.3

permissions:
  contents: write # Permissão para criar o release

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente .NET 8
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3. Restaura as dependências do projeto
      - name: Restore dependencies
        run: dotnet restore ReleaseZipper/ReleaseZipper.csproj

      # 4. Publica o projeto em uma pasta simples e previsível ('./publish')
      - name: Build and Publish
        run: >
          dotnet publish ReleaseZipper/ReleaseZipper.csproj
          --configuration Release
          --runtime win-x64
          --self-contained true
          -p:PublishSingleFile=true
          --output ./publish

      # 5. Cria o ZIP sem usar 'cd', evitando a confusão de caminhos
      - name: Create ZIP Archive
        run: 7z a ReleaseZipper-${{ github.ref_name }}.zip ./publish/*

      # 6. Cria o Release no GitHub e faz o upload (agora ele vai encontrar o arquivo)
      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ReleaseZipper-${{ github.ref_name }}.zip
          body: Release gerado automaticamente a partir da tag ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}