name: ReleaseZipper Release

on:
  push:
    tags:
      - 'v*'   # Só roda quando você cria uma tag tipo v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Compilar ReleaseZipper (self-contained exe)
      run: dotnet publish ReleaseZipper/ReleaseZipper.csproj -c Release -r win-x64 `
             --self-contained true `
             /p:PublishSingleFile=true `
             /p:InformationalVersion=${{ github.ref_name }}

    - name: Empacotar ReleaseZipper-${{ github.ref_name }}.zip
      run: |
        cd ReleaseZipper/bin/Release/net8.0-windows/win-x64/publish
        7z a ../../../../ReleaseZipper-${{ github.ref_name }}.zip *

    - name: Publicar no GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: ./ReleaseZipper/bin/Release/net8.0-windows/ReleaseZipper-${{ github.ref_name }}.zip
        body: "Release gerado automaticamente a partir da tag ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
