name: Build and Release

on:
  push:
    tags:
      - 'v*' # Dispara o workflow em tags como v1.0, v1.2.3, etc.

permissions:
  contents: write # Necessário para criar a Release e fazer upload de arquivos

env:
  PROJECT_PATH: ReleaseZipper/ReleaseZipper.csproj
  # Define um diretório de saída simples e previsível para os artefatos
  ARTIFACTS_DIR: release-artifacts

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build and Publish
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            --output ${{ env.ARTIFACTS_DIR }} # <-- Força a saída para uma pasta simples

      - name: Create ZIP archive
        # Cria um ZIP na raiz do projeto contendo tudo que está na pasta de artefatos
        run: 7z a ReleaseZipper-${{ github.ref_name }}.zip ./${{ env.ARTIFACTS_DIR }}/*

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v2 # Use a v2, que é mais recente
        with:
          # A action agora encontra o arquivo ZIP facilmente na raiz do projeto
          files: ReleaseZipper-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
