name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ReleaseZipper/ReleaseZipper.csproj

      - name: Build
        run: dotnet publish ReleaseZipper/ReleaseZipper.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Zip build
        run: |
          cd ReleaseZipper/bin/Release/net8.0-windows/win-x64/publish
          7z a ../../../../ReleaseZipper-${{ github.ref_name }}.zip *

      - name: Debug arquivos gerados
        run: ls -R ReleaseZipper/bin/Release/net8.0-windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./ReleaseZipper/bin/Release/net8.0-windows/ReleaseZipper-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
